#!/bin/bash
set -e

POSTGRES_USER="admindrap"
POSTGRES_PASSWORD="admin3312Drap"

POSTGRES_DB="n8n"
POSTGRES_NON_ROOT_USER="mavis"
POSTGRES_NON_ROOT_PASSWORD="mavispassword"

echo "SETUP INFO: Using POSTGRES_NON_ROOT_USER=$POSTGRES_NON_ROOT_USER"
echo "SETUP INFO: Using POSTGRES_NON_ROOT_PASSWORD=<hidden>"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
EOSQL