version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=default_user
      - POSTGRES_PASSWORD=default_pass123
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=default_user
      - POSTGRES_NON_ROOT_PASSWORD=default_pass123
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U default_user -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - caddy

  n8n:
    image: docker.n8n.io/n8nio/n8n
    deploy:
      labels:
        caddy_0: "n8n.saguarodrap.dev"
        caddy_0.reverse_proxy: "{{upstreams 5678}}"
        caddy_0.tls: "davidake117@gmail.com"
        caddy_0.tls.on_demand:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=default_user
      - DB_POSTGRESDB_PASSWORD=default_pass123
      - N8N_HOST=n8n.saguarodrap.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.saguarodrap.dev
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - caddy
networks:
  caddy:
    driver: overlay
    external: true
